// Generated by CodiumAI

describe('code snippet', () => {

    // Returns global time context when no viewKey is provided
    it('should return global time context when no viewKey is provided', () => {
        const openmct = {
            objects: {
                makeKeyString: jest.fn()
            }
        };
        const timeAPI = new TimeAPI(openmct);
        const result = timeAPI.getContextForView([]);
        expect(result).toBe(timeAPI);
    });

    // Throws an error when objectPath is null or undefined
    it('should throw an error when objectPath is null or undefined', () => {
        const openmct = {
            objects: {
                makeKeyString: jest.fn()
            }
        };
        const timeAPI = new TimeAPI(openmct);
        expect(() => timeAPI.getContextForView(null)).toThrow('No objectPath provided');
        expect(() => timeAPI.getContextForView(undefined)).toThrow('No objectPath provided');
    });

    // Throws an error when objectPath is not an array
    it('should throw an error when objectPath is not an array', () => {
        const timeAPI = new TimeAPI();
        expect(() => {
            timeAPI.getContextForView();
        }).toThrowError('No objectPath provided');
    });
});
